export const carContent = {
    sections: [
        // Chapter 1
        {
            chapterNumber: "01.",
            chapterTitle: "The History of HCI in Automobiles",
            subsections: [
                {
                    title: "",
                    content: `Amidst countless other artifacts of the Industrial Revolution, the automotive was one that changed the course of history for the world as the influence from its invention rippled across various aspects of daily life. It proceeded to shape entire economies across the globe, transform the very fabric of society and cemented its position as both a ubiquitous and vital part of everyday life–particularly in the car-centric context of the United States.`
                },
                {
                    title: "An Essential Tool for Living",
                    content: `Pertaining to society specifically, the automobile played a pivotal role in shaping numerous aspects of the urban landscape of the 20th century. Cities which had once been planned and built around pedestrian-centric paradigms now found themselves with the option to expand rapidly as the automobile made commuting over distances significantly easier. This in turn led to the rise of 'suburbia' and suburban living as populations shifted to living further from city centers and commuting to work by their cars. As people moved to suburban developments, these areas were often spread out, with single-family homes and properties dispersed over large areas due to the fact that they were designed with the car in mind. This resulted in people relying on their cars as more of an essential tool for enabling their everyday lives as compared to a luxury item, and significant amounts of time was spent in their vehicles as they commuted between work, school and errands.
                    
                    In turn, automakers started to place greater emphasis on comfort, convenience and the overall experience of their products to differentiate themselves in the rapidly growing automotive industry. No longer was the automobile just a tool for commuting, it grew to be a symbol of status–for many it became a reflection of their personal tastes and lifestyle. Various technologies such as Power Steering, the Automatic Transmission and the Bench seat started to emerge during the Postwar Era of the 1950s. But it wasn't until the 1960s where automakers started to take ergonomics and adjustable features into consideration with the introduction of adjustable seats and steering columns for better customization per driver, leading to drastically increased comfort, especially for drivers spending multiple hours in their cars each day. Air conditioning was another milestone feature introduced in some higher-end vehicles, allowing for adjustment of the conditions for its occupants.`
                },
                {
                    title: "The Age of Technology",
                    content: `With the advent and meteoric rise of consumer technology in the 1980s such as radios, computers and more portable formats of media like cassette players, automakers began to look towards introducing these features as part of the overall in-car experience of their products. Computers on cars, specifically Electronic Control Units (ECUs) allowed for the aggregation and distribution of data, leading to the first implementations of digital dashboards that provided information on speed, fuel levels and other critical data such as ones found on the 1985 Citroen BX Digit designed by Marcello Gandini. (Noe) In-car navigation systems were one of the earliest forms of in-car infotainment technology in the 1990s, showing up on high-end luxury vehicles as they were typically bulky and expensive at the time. These systems were primarily CD-ROM-based and utilized GPS to provide aural turn-by-turn navigation through the audio system of the vehicle. In 1995, BMW integrated GPS navigation with a digital map display on the E38 7 Series; creating one of the first digital interfaces in automobiles. This followed through the millennium with BMW releasing the very first iDrive system (one that they still use today with the latest version at 8.5 as of this writing) in 2001. It was considered a significant milestone in the evolution of technology in automobiles as this was a shift towards centralized, fully integrated digital infotainment systems, combining navigation, media, vehicle data, air conditioning, and more into a single digital interface. The system also featured a single physical central rotary dial for controlling the multiple in-car systems–a significant step forward in human-computer interaction within the confines of the automobile. (BMW Group)`
                },
                {
                    title: "The Infotainment System",
                    content: `For the most part of the 2000s, the car infotainment experience largely centered around traditional analog and physical interfaces involving button-based controls, knobs, sliders, and dials. These adjusted functions like audio volume, the temperature of the climate control, and seats. Digital displays providing various vehicular functions and information were present but limited and controlled by the aforementioned physical means. Functions were decentralized and fragmented and users were often required to acquaint themselves with a high number of physical controls scattered around the cockpit and dashboard that pertained to each vehicular function respectively. (Noe)
                    
                    It was not till 2007, with the release of the iPhone with its revolutionary touchscreen technology and associated user experience as well as its gradual mass adoption over the following years that infotainment technology in cars took yet another significant step forward. With newfound affordances pertaining to touchscreen experiences and the philosophy of having a screen being a medium of high versatility due to its ability to display basically endless permutation of body conceivable, automakers began rethinking and shifting their methodologies and approach towards digital interfaces in vehicles.

                    In 2010, Ford introduced MyFord Touch, which was one of the first infotainment systems designed around a touchscreen user experience; with a multi-touch display for controlling infotainment functions. Touchscreen technology and user experiences only then proceeded to snowball forward in between the years of 2010 and 2013 with more automakers introducing their respective implementations in their products. MyLink from Chevrolet, Entune from Toyota, Connect from Nissan, and MMI Touch from Audi are some examples of infotainment systems featuring multi-touch capacitive touchscreens and gesture controls from the timeframe. Tesla in particular introduced an infotainment system for their Model S product in 2012 with a huge 17-inch touchscreen as its centerpiece and a design approach that was more like that of a Silicon Valley company startup compared to a traditional automaker. This resulted in a bill of materials (BOM) for the system that was roughly twice the cost of the highest-end infotainment unit examined by analysts in the automotive industry. 
                    
                    In 2014, Apple entered the fray with CarPlay, allowing iPhone users to integrate their iOS devices with their car's infotainment system. This was a significant move as it further integrated a user's experience with their vehicle. The synergy between a user's iPhone and the car via CarPlay created a seamless environment where personal messages, music, calls, and saved navigation could now be interfaced directly via the car's infotainment system. Google followed a year later with the introduction of Android Auto, offering users within their Android ecosystem a similar level of integration that CarPlay offered. These two platforms from Apple and Google served to provide a unified experience between a user's personal device and their vehicle.`
                },
                {
                    title: "Users and Industry Response",
                    content: `User reception, however, has been mixed as the automotive industry trended toward the development of integrated touchscreen infotainment systems after 2015, with both appreciation and notable criticism that persist to this day. Notable concerns revolve around the complexity and usability of touchscreen interfaces, as well as safety issues with the touchscreen interfaces being distracting and difficult to use without taking their eyes off the road due to the lack of tactile feedback.

                    This has led to an even more varied response from the industry, with automakers the likes of Tesla doubling down on their ethos of a single integrated touchscreen approach towards their infotainment experience first seen with the launch of the Model 3 in 2017 that has carried through to their products of today as seen in the Cybertruck launched in 2023. While automakers like Volkswagen and Aston Martin are paying much closer attention toward striking a balance between physical controls and touchscreens. "We've all reached peak screen." according to Alex Long, Aston Martin's head of product and market strategy. "People are frustrated by them in some of the research we've done, particularly in performance cars. They don't want their eyes off the road." (Nonemacher) Volkswagen has even gone so far as to commit to reintroducing physical controls in their newest lineup of cars. "From the ID 2all onwards, we will have physical buttons for the five most important functions – the volume, the heating on each side of the car, the fans, and the hazard light – below the screen.", "They will be in every car that we make from now on. We understood this" says Andreas Mindst, Volkwagen's design chief.
                    
                    As automakers continue to navigate striking the balance of infotainment systems of today, one thing is clear; I have found myself with a particularly wicked problem. This is a problem that is multi-pronged, it is challenging to find consensus or agreement and has been ever since the introduction of touchscreen technology more than a decade ago. It resists quick fixes and does not have a clear-cut universal solution. It is one that is entrenched deep within the ever-evolving landscape of technology and as a result, only evolves and transforms over time as users' acquaintance grows and affordances shift accordingly. 
                    
                    This has been a field of Interaction Design that I have had an interest in delving deeper into for quite some time now. It is a delicate balance between the analog and digital experience within the confines of a car and I do believe automakers to still be deep in the midst of striking that balance; a very wicked balance that I would like to personally explore as part of my journey as an Interaction Designer.
                    
                    
                    
                    `
                }
            ]
        },
        // Chapter 2
        {
            chapterNumber: "02.",
            chapterTitle: "Metaphors: The Automobile as a Third Place",
            subsections: [
                {
                    title: "",
                    content: `As a start, I was adequately tempted to study touchpoints littered across the dashboard of an automobile with the intent to extract metaphors from them, with the irony that the dashboard itself being quite possibly the largest and most literal metaphor on an automobile having being not lost on me; its etymology traces back to wooden barriers positioned at the front of horse-drawn carriages to protect occupants from mud and debris "dashed up" by the horses before them. The steering wheel, indicator stalks, the bench seat, airbag, trunk, I could go on. The interior of an automobile is positively ridden with metaphors to this day; artifacts from a bygone era as the world shifted from horse-drawn carriages to the automobile, all serving to ease individuals into the mechanics of an automobile without being instructed. Interestingly, as plentiful as metaphors are within the interior of a car, there equally exists terminology that began life within the automobile itself and consequently went on to serve as metaphors that exist in our daily vernacular today. Pulling the handbrake as an example off the top of my head and going full throttle as another, the subject matter of both examples are the very names of vital components of the automobile–this only highlights the lasting impact and pivotal role the automobile played in not only building modern society but also shaping it.

                    The above two paragraphs alone are sufficient to stir an entire discourse about metaphors and their roles in the interior of automobiles. However, a sprinkle of masochism runs in my veins and I made a decision to look beyond. I began by querying individuals with the following two questions: 1. What does the car mean to you? 2. If you could describe being in a car as an environment, what would it be? The answers I received were downright fascinating, ranging from 'transportation tool', to 'my partner', to 'a place to cry in', it was clear that while the automobile may be viewed as just an appliance by some, it is also something that is fundamentally deeply personal and difficult to form a common consensus on what it really is. This led me down yet another rabbit hole and I began to search for parallels in our daily lives, ultimately looking inward and landing with one that is both close to the ground and heart for many New Yorkers: the third place.`
                },
                {
                    title: "The 'Third Place'",
                    content: `A quick crash course before proceeding: The concept of a "third place" was first introduced by sociologist Ray Oldenburg in his book The Great Good Place (1989). Simply put, A third place refers to a social environment that is distinct from the first place (home) and second place (work), where people gather, interact, and build community. A space that is informal, and personal to one. (Oldenburg 1989)

                    While third places are traditionally associated with social interaction and community, they are also commonly used by people for solitude and personal reflection away from their aforementioned first and second places. An example of this could include someone who works in a high-stress job routinely taking the time to disconnect, reflect, and mentally reset at a park bench before heading home from work. This is not dissimilar to a role that automobiles are already serving in modern society for many people today; the enclosed environment of a car offers a unique setting where one can conduct activities away from external distractions. This manifests itself in numerous ways, from providing a private space for reflection, emotional release, or solitude to a space for community bonding through karaoke sessions on road trips or even business conference calls if we're to swing to the opposite end of the spectrum. (Zeman)`
                },
                {
                    title: "COVID-19",
                    content: `However, just as much as the automobile experience is being constantly redefined, so is the very concept of the third place. The COVID-19 pandemic altered behaviors within society and shifted how people interacted with third places. As lockdowns and restrictions limited access to physical public spaces, the concept of the third place revolving around communal spaces such as coffee shops, libraries, parks, and bars had to be redefined. This, combined with many individuals choosing to instead seek solitude and privacy during the lockdowns gave rise to a new form of third place. Cars began to take on the role of a personal refuge and workspace (Volpe). Studies have shown that 75% of Gen Z individuals now view their vehicles as a third place, indicative of the increasing desire for privacy, flexibility, and autonomy in a post-pandemic world. The rise and constant evolution of in-car infotainment systems with more integration of technology and enhanced connectivity, as covered in my earlier writing, likewise served as a catalyst in spearheading this shift towards the car as a portable sanctuary where individuals can engage in a wide range of activities at their will. This usage aligns with the post-pandemic culture of increased remote activities and the desire for flexibility in work and leisure. (Sanchez)


`
                }
            ]
        },
        // Chapter 3
        {
            chapterNumber: "03.",
            chapterTitle: "The Human Driver as an Algorithm",
            subsections: [
                {
                    title: "",
                    content: `In the words of Kyle Chayka, in his book titled Filterworld, he ascertains that the algorithm that we're most acquainted with today is actually shorthand for "algorithmic recommendations", the digital mechanism that absorbs piles of user data, push it through a set of equations and spit out a result deemed most relevant to preset goals. Throughout his book, he elaborates on how these algorithmic recommendations are disproportionally shaping the vast majority of our culture today through both digital and physical spaces. He states that small decisions in the past used to be made one at a time by humans: A newspaper editor decided which stories to put on the front page, a magazine photo editor selected photographs to publish, and an independent radio station DJ assembled playlists of songs that fit their own mood and particular vibe of the day or place. While these decisions were of course subject to various social and economic factors of the day, the person in charge of them ultimately ensured a basic level of quality, or even safety, that can be missing from the internet's algorithmically accelerated feeds of today. This perspective of his views algorithms and humans as mutually exclusive entities, with one replacing the other in one scenario and with the human being subservient to the algorithm in others.`
                },
                {
                    title: "Autonomous Driving",
                    content: `In the context of the automobile, it is extremely easy to draw parallels between the human and the algorithm with the rapid development of autonomous driving technologies. This was first widely implemented by Tesla in 2014 when it began including hardware sensors (Hardware 1 - HW1) in its vehicles, and the first Autopilot software update (v7.0) enabling features like lane keeping, adaptive cruise control, and limited self-steering releasing the following year ("Tesla Rolls Out Autopilot Technology"). Around the same time, Google's Self-Driving Car Project began to reach maturity, rebranding itself to what we know today as Waymo, with the first fully driverless ride-hailing service launching in Phoenix, Arizona in 2018 ("About Waymo"). These were monumental steps towards the vision of fully autonomous vehicles, allowing people the ability to commute with all the same benefits that the automobile would provide while removing the vexing frustrations of having to operate the automobile manually–yet another stellar example of the algorithm replacing the human.

                    While it is easy to dive deep into the rabbit hole that is autonomous technology today, I would like to instead take a step back and entertain a more thought-provoking perspective; that the human is in itself an algorithm, in the very same vein as to what drives a mosquito to seek heat, a moth towards light, and Icarus towards the sun. From the perspective and end goal of navigation, the human has always fundamentally operated as an algorithm in support of that; be it on foot, on horseback or within the confines of their portable sanctuary that is the automobile. The human driver, much like an algorithm, is an information-processing entity. Just as much as algorithmic recommendations are informed by user patterns for optimal responses, human drivers actively analyze and gather data from their surroundings in real-time to inform optimal driving decisions.`
                },
                {
                    title: "The Human Driver",
                    content: `The human driver is constantly filtering information, prioritizing the safety of pedestrians, and obeying traffic signals and road signs to ensure they are within the legal jurisdiction in which they are operating. Predicting behavior is crucial in the act of driving by anticipating how other road users or even animals might act in relation to them, with human drivers developing a more acute intuition for road situations over time not unlike the mechanics of machine learning that form the backbone of recommendation algorithms today. Lastly, human drivers modify their behavior in real-time based on the aforementioned conditions, mechanical feedback, and stimuli from the vehicle itself, be it a congested pedestrian-heavy environment or the increased load on the steering wheel one might encounter while taking a tight corner at a speed that might be higher than what is appropriate for it. 

                    Just as much as there are numerous algorithmic recommendation models the likes of one we may find on Amazon, Spotify, and Instagram each operating on vastly different datasets and weighting systems resulting in varying outcomes serving the business goals of the respective platform, there exist different driving styles that stem from countless unique driver personas on the road; each having an influence on the design of automobiles. 
                    The luxury human driver for example, prioritizes comfort and status, which results in the design of a smooth-riding automobile with relaxation and a high-end experience in mind. An emphasis on effortless and minimal comes to mind, with noise reduction, pinky-finger-light steering, and carefully calibrated power delivery being key features found in high-end luxury automobiles, with Rolls Royce motor vehicles as a shining pinnacle of this market segment.

                    On the other end of the spectrum, we have the performance human driver seeking an outsized focus on engagement, control, and responsiveness in their vehicles of choice. Performance cars are designed with the paradigm of offering maximum feedback from both the car and the road in mind. Manual control is often preferred over automated assistance, with the ultimate north star of the vehicle feeling like it is operating as a natural extension of the driver. The 2025 Porsche 911 Carrera T exemplifies this philosophy by featuring a six-speed manual transmission with a traditional clutch, emphasizing mechanical feedback and driver involvement. This model is specifically designed for driving purists who appreciate the tactile experience of manual gear shifting (Neil).

                    Right in the middle, we have the commuter human driver, one that prioritizes efficiency and convenience. This is a segment that seeks to maximize route efficiency and prefers automation the likes of adaptive cruise control and lane keep assist for routine point A to B commuting. As such, vehicles within this segment are likely to be designed with efficiency and reliability in mind, with hybrid or electric powertrains and off-the-shelf components. A striking example of this would the Toyota Prius gaining mainstream adoption in the mid-2000s with the introduction of its second-generation model, pushing the model line to the top as one of the best-selling hybrid vehicles worldwide.`
                },
                {
                    title: "Human Driver Personas",
                    content: `The design of the automobile started off monolithic with the Model T in 1908, however throughout the decades since it has become anything but. As vehicles evolved over the years, so did the human drivers themselves, ultimately forming vastly different personas operating on different modalities and seeking different outcomes of their own; consequently carving out distinct market segments. This has resulted in the design of automobiles that differ vastly from each other. Today, as automation powered by machine learning algorithms begin to not only mirror human driving algorithms, but surpass them, uncertainty grows on whether the human driver will remain a core part of the equation or be replaced by it entirely not unlike the newspaper editor, magazine photo editor, and the independent radio DJ. 

                    As of this writing in March 2025, equestrianism stands as a professional sport recognized by the International Olympic Committee despite the fact that the world collectively moved on from horses in the early 1900s. Porsche is expanding its lineup of cars equipped with manual transmissions with an increased take-up rate from its customers even though the automatic transmission has been a standard comfort feature since the 1950s (Hodge), and Hyundai is introducing simulated shifting in their Ioniq 5N in spite of the fact that it is an Electric Vehicle (EV) and that EVs do not have gears to shift through (Hogan). Just as much as McNally Jackson stands as a bastion of the human-curated bookstore experience against Amazon and its recommendation algorithm for books, the lens of history has shown that there will always be alternatives willing to design experiences for the human driver algorithm–in defiance of the ever-evolving norm of algorithms increasingly designed for the purpose of automation today.
                    
                    
                    
                    
                    `
                }
            ]
        },
        // Chapter 4
        {
            chapterNumber: "04.",
            chapterTitle: "A love letter to the Porsche 911",
            subsections: [
                {
                    content: `As the design of the automobile began to mature around the middle of the century with the introduction of creature comforts, it began to take on a new role as a status symbol as it splintered into market segments that sought to deliver a product designed for the many specific demographics of drivers. Accordingly, the question of taste goes in hand with the concept of a status symbol: what exactly is taste, who defines it, and what does it mean on a personal level when a choice is made to drive a low-slung 1969 Corvette Stingray over a Plymouth station wagon of the day?`
                },
                {
                    title: "'Taste'",
                    content: `In the words of Ruby Justice Thelot in his essay "A History of Taste: Taste and Morality", Taste sought to be the answer to the meandering, it was the differentiator between the unprincipled garish spending of trade merchants and the virtuous aesthetic decision of the nobility. But with the dawn of the Industrial Revolution giving rise to the bourgeoisie who were granted unfettered access to luxuries previously only held by the aristocracy; the lines blurred and the moral aristocratic tastes of the noble had to adapt to a growing capitalist economy and its demands for consumption. This paradigm has persisted to this day as we find ourselves in what is often cynically referred to as late-stage capitalism, where the choice to don uncreased white sneakers over polished penny loafers was one of personal taste driven by capitalistic consumption and not aristocratic morals.

                    But what exactly does it mean to design for an uncreased white sneaker-wearing crowd? What are the specific choices that have gone into the design of it and how have they been influenced by consumer demands over history? In order to tackle this question and to bring our discussion back to the automotive industry; we look towards a storied icon, one that belongs not only in the annals of the automobile industry but in design as one of the most significant design artifacts throughout modern history: the Porsche 911. For the most part of its lineage since its introduction in 1964 by Ferdinand Porsche, the Porsche 911 has been commonly referred to as the "ultimate all-in-one car"; which is a bold statement if not for the fact that it confidently delivers on it. To gain a better understanding, we will have to dive deeper into two (out of many) archetypes in automotive design; namely the Grand Tourer (GT) and Motorsport racing, and identify how these fields have influenced the design and cachet of the Porsche 911 as a prime intersection of both philosophies. Buckle up.`
                },
                {
                    title: "The Grand Tourer",
                    content: `The Grand Tourer (from the Italian Gran Turismo), colloquially referred to as the GT today, was an automotive design archetype and philosophy birthed in a post-WWII Europe economy. Vibrant with optimism and a booming economy, the wealthier class of the day looked towards cars beyond what was deemed conventional, a vehicle that would allow them to go on "Grand Tours"; a concept originating from the 17th–19th centuries where aristocrats embarked on extended journeys across Europe to experience art, architecture and culture. Thus the demand for the automotive equivalent of first-class travel was born; an automobile that is not necessarily the fastest vehicle on the road, but one that is guaranteed to allow you to cover long distances in elegance, serenity, and style–with room for two and associated belongings. These cars were designed with a sense of elegance and proportion in mind, reflective of the class of its buyers. This manifested in a design language that is often understated but aesthetic-forward with long hoods, sweeping rooflines, and low stances. Drabbed in wood and leather, the interiors of these GT cars were closer in likeness to the jazz lounge at a country club than the relatively spartan interiors one would normally expect from an automobile. 

                    Eager to capture this new market segment of drivers, luxury automakers of the day ended up designing some of the most influential and iconic automobiles in history. Ferrari introduced the famed 250 Lusso line in 1952, the 250 GTO variant of the lineup went on to be arguably one of the most valuable collector cars in the world today. In 2018, a 250 GTO 3413GT sold for $48,405,000 at an RM Sotheby's auction, representing a new record for the most expensive car ever sold at an auction then (RM Sotheby's). Mercedes-Benz entered the ring in 1954 with their two-seater GT car; the 300 SL. Known for its iconic gullwing doors and its timeless looks, the 300 SL gained status as a highly influential grand touring automobile, with a 300SLR variant selling at an auction for $143 million in 2022, unseating the previous record held by the Ferrari 250 GTO by an astronomical margin (McAleer). Countless other automakers joined the fray with their GT offerings, notably Aston Martin with the DB5, which led to the brand's iconic association with James Bond. Jaguar with the E-type, and last but absolutely not least, Porsche with the 911.

                    From the design language influenced by the needs of its class of buyers to the eyewatering values that these vehicles hold to this day, it is clear that GTs are automobiles that are a reflection of taste and not just function. GTs are designed specifically for those who see cars as part of their lifestyle and what they stand for, not merely tools; a taste for luxury over utility and sophistication in the way they approach their lives.`
                },
                {
                    title: "Motorsport",
                    content: `On the other extreme end of the spectrum, we have Motorsport. A motorsport-derived car is the mechanical equivalent of an athlete: purpose-driven, lean, focused. Design principles of speed, precision, and endurance under extreme conditions are key. These practically mirror the needs of the users of this automotive archetype; racecar drivers are arguably athletes in their own right, enduring extreme conditions for prolonged periods of time throughout the races, with the renowned 24 hours of Le Mans requiring drivers to race for quite literally up to 24 hours. These cars are built to excel at the edge. Interiors of these cars can be so bare that insulation is often not even part of the equatio. Door handles are fabric pull loops, and brand logos are vinyl stickers instead of actual metal emblems. These design principles add credibility to the trained enthusiast's eye as the purest manifestation of form following function; they represent skill-based taste. For one to truly enjoy these cars, they must meet it in the middle with vim and vigor.

                    Amidst the countless legends in motorsport history the likes of the Ferrari F40, Ford GT40, and McLaren F1 GTR stands the Porsche 911 as an equal giant in this territory. Not only was the 911 originally introduced as a GT car in 1964, but it is a model line that has also participated in nearly every form of motorsport in its storied history–rally, endurance, GT, and Hillclimb, with the 911 RSR notably being an iconic product for the brand in regards to motorsport. This has given the Porsche 911 the unique position of being a product that is birthed from two separate pedigrees.`
                },
                {
                    title: "Porsche's Product Lineup Strategy",
                    content: `As such, what does it mean for someone to drive a 911 today? Are they a driver who values an elevated sophisticated experience capable of covering long distances reliably or are they one who prefers the raw engagement of operating a machine at its limits? 

                    The answer to this comes with the way Porsche has acutely recognized its prestige and smartly diversified its offerings even within a single lineup to cater to various tastes. Today, on Porsche's website for the 911 line, you will find yourself with 19 separate models of the 911, a staggering number that generously excludes limited edition models that are not commonly listed on their site. Most automakers have a reputation for catering to the specific tastes of drivers be it intentionally or otherwise; BMW drivers are known to develop a cognitive disability towards the usage of their turning indicators, Lamborghinis are singularly known to err on the side of ostentatious luxury in spite of their remarkable performance and engineering, and Jaguars tend to be driven by retirees. But within the car community, the Porsche 911 driver is seemingly immune to this; a driver who has chosen to drive a 911 over a BMW M performance car or a Jaguar F-Type is more often than not viewed as someone with 'more taste'–this is due to the diversified lineup for the 911. 

                    Porsche as a brand has successfully balanced tradition and innovation throughout its history, with a close focus on its customer segmentation and respective feedback from each segment that influences its product strategy in its lineup. While the silhouette and rear-engine layout of the 911 remains a constant not only within the lineup but also its design evolution throughout history, the design principles that inform the experience of each model couldn't be any more different. A prospective 911 driver who prioritizes a GT experience would turn towards a 911 Carrera, Targa, or Turbo where they will find a solidly built, luxurious, and reliable daily cruiser that can cover long distances with ease. On the other hand, a driver in search of the rawest, most exhilarating, ear-shattering experience would find their muse in the track-focused models the likes of the 911 GT3, GT3 RS, and GT2 RS. 

                    The Porsche 911 is a vessel of layered tastes stemming from vastly different pedigrees and engineering philosophies over the decades, and instead of a product that has ultimately consolidated into a muddled experience, it has found itself on the opposite end of the spectrum as a product line proficiently catering to a diverse plethora of tastes. 

                    It is often joked that only dentists are able to afford a Porsche 911, but due to the aforementioned legacy and quiet sophistication associated with the model lineup, it is just as likely that one may witness that same dentist tearing down the straights of Laguna Seca on a weekend in their GT3 RS. Only then may one validly utter the words: "Damn, does that guy have taste."
                    
                    
                    
                    
                    `
                }
            ]
        },
        // Chapter 5
        {
            chapterNumber: "05.",
            chapterTitle: "A Preservation of the Analog Experience",
            subsections: [
                {
                    title: "",
                    content: `While much of the conversation around taste revolved around the different archetypes of vehicles, the fundamental idea of the automobile for the most part of history since its conception remained the same: a manually controlled, ICE-propelled vehicle as a means of getting around. However, today, we find ourselves in the middle of a massive upheaval in the automotive industry due to the rise of AI-driven automation and the increasing electrification of vehicles replacing the traditional Internal Combustion Engine (ICE) as a means of propulsion. Within the books of history, we find waves of technology continuously reconfiguring what's considered normal for the time. This applies not just within the context of automobiles, but across all industries; including creative, technical, and service-based. Once indispensable workflows are rendered obsolete each time. 
                    
                    Erin Malone writes about this phenomenon in her article "Lessons from Technology's Past: Navigating the AI Future". Not only was the article acute in its portrayal of the various upheavals in the publishing industry with the introduction of the Linotype in the 1920s replacing earlier printing methods brought about by the Gutenberg printing press as an example, Erin more importantly speaks about the displacement of entire workforces. This was most apparent in the digital desktop publishing revolution that began around the 1970s with a combined effort from Douglas Engelbart's work, Xerox PARC, and Adobe's PostScript. Entire categories of production roles disappeared almost overnight, with paste-up artists, typesetters, pre-press camera operators, and film separators finding their craft obsolete. Professionals who had been critical to the print production process suddenly found themselves without a place in the new digital world; what was considered normal in the physical publishing world then was no longer–digital desktop publishing was the new normal, and the workforce requirements shifted accordingly.`
                },
                {
                    title: "The Autonomous Driving Revolution?",
                    content: `Today, with the development of Advanced Driver-Assistance Systems (ADAS) and autonomous self-driving functionalities within automobiles; we find ourselves with not just a technological evolution in the history of the automobile, but a cultural and cognitive revolution. What's considered normal when it pertains to human involvement in mobility is being redefined–is the driver now an operator, or a supervisor? However, if we were to extract an analog from Erin's world of publishing and more specifically the act of printmaking, we can draw historical precedence that historical technological shifts don't necessarily completely eliminate traditional methods, but instead recontextualize them as forms of appreciation, craftsmanship and dare I say, taste. Letterpress, risograph, and screen printing were once printmaking processes that were considered the defacto process for publishing. If anything, these are processes that replaced one another as technological advancements of their day. However, these processes still persist to this day and are instead treasured for their tactile imperfection and human touch. 

                    Quite recently, I found myself at a talk by Amos Paul Kennedy Jr. held at the School of Visual Arts (SVA) and the not-insignificantly sized theater then was filled to the brim with students, faculty, and industry professionals alike. Amos is a renowned letterpress artist who works with handset wood, metal type, and oil-based inks. That entire evening, Amos exuded raw passion for the craft of letterpress, even going so far as to proclaim with a fiery, booming voice, that he loves nothing more than being at the printing press. The audience was captivated, there simply wasn't time for all the questions to be answered within the session. One thing was clear that night: a love for the analog still persists in spite of technological advances, and this love wasn't held just by practitioners, but by the partakers as well.

                    And so, while automation and electrification are reshaping both the experience and human involvement of driving, it wouldn't be too far of a stretch to say that the desire for a visceral, analog experience persists within the context of the automobile as well. If anything, and within some circles, it grows stronger. For a deeper understanding of this, we will dive into two emergent fields of automotive design philosophy today.`
                },
                {
                    title: "The Manual Transmission",
                    content: `The first would be the persistence of the manual transmission, a technology within automobiles that is logically and objectively antiquated but yet curiously is still around today, and even desired. Early automobiles employed transmissions that were controlled manually as the driver cycled through gears that best suited the current power band of the engine at the relative speed of the vehicle. It was not till the 1950s that technological and engineering processes advanced enough to automate the process of shifting gears; the driver now had one less factor to consider in the operation of an automobile. The automatic transmission went on to gain traction and eventually became the norm within vehicles globally in the 70s onwards. However, despite the overall decline over time, the manual transmission endures in a specific slice of the automotive market to this day: the enthusiast-driven performance car. Many manufacturers retain manual options in their offerings, not for mass appeal, but for cultural and emotional relevance. To drivers who opt for a manual transmission over the default automatic option today, it is a deliberate, identity-forming decision. Not unlike the tactile imperfection of handprinted posters, driving a manual automobile well demands a level of finesse and practice from drivers operating it; providing a sense of satisfaction when mastered. In 2024, the manual transmission take rate for the Porsche 911 in the U.S. stood at 37% of owners and at 43% for the 718 Boxster and Cayman models ("Decoding Porsche's Current 911 Manual Transmission Strategy"). For many enthusiasts, it transforms the mere act of commuting into a craft. The gearshift becomes an extension of their body. The manual transmission persists to this day, much like film photography and mechanical watches, not despite progress but because of it–an experience that offers tactility and imperfection in spite of increasing perfection brought about by technological advances.`
                },
                {
                    title: "Simulated Analog Experiences in EVs",
                    content: `The second field of study revolves around engineering artificial analog experiences into the increasingly automated and perfect experiences of Electric Vehicles (EVs) by automakers seeking to satisfy a market craving for sensation and feedback. For this we will be diving deeper into the Hyundai Ioniq 5N, a performance EV offering by Hyundai. Recognizing the lack of driver engagement in EVs due to their silent operation and seamless linear acceleration, Hyundai sought to infuse the performance variant of their Ioniq 5 model with the tactile and auditory sensations one would traditionally associate with the relatively analog experience of ICE performance cars. Introducing the N e-Shift, the system simulates the gear shifts of a dual-clutch transmission by modulating the normally linear torque curve of the electric motors, providing drivers with the analog jolt between shifts. Paddle shifters on the steering wheel allow for manual control of the 'gears'. On the surface, this is an engineering exercise that is entirely superfluous; electric motors do not require gears, and they absolutely will not jolt you in between 'shifts'. However, when paired with the N Active Sound+ feature that provides a futuristic soundtrack that modulates accordingly with the speed and gear shifts of the vehicle, the Ioniq 5N provides enthusiast drivers with a simulated analog experience that has been widely praised by automotive journalists and enthusiasts; with the 5N ranked #1 in Best Electric Compact SUVs by Car and Driver and a 9/10 rating by WIRED.`
                },
                {
                    title: "There is still hope.",
                    content: `Throughout history, progress has time and again rewritten norms; this is a given constant. But so too is the deeply human desire to stay engaged within the tools we choose to hold on to and remain engaged with, whether it's printmaking in the shadow of digital publishing, or manual driving in the age of autonomous driving and EVs. As technology continues to surge forward in the overdrive gear, we may find some in reverse; seeking not nostalgia, but a preservation of the analog experience and as a form of identity. 

                    In a world where Claude Monet's Water Lillies mounted on a wall of MoMA coexists with Midjourney as a tool, so too will one observe a 2025 Porsche 911 Carrera T equipped with a manual transmission alongside a Tesla Model 3 with autopilot enabled headed not only down 5th Avenue but into the future as a dichotomy that remains ever constant.
                    
                    
                    
                    
                    `
                }
            ]
        },
        // Chapter 6
        {
            chapterNumber: "06.",
            chapterTitle: "Progress or Preservation?",
            subsections: [
                {
                    title: "",
                    content: `The story of the automobile has always been one of movement; of mechanical progress, cultural shifts, and most importantly (within the context of these essays at least), design and technological innovation. Cars are often discussed in terms of convenience, functionality, and comfort, as tools of commute, to get from point A to B. Yet beneath these tools lies something far more human, as covered in the previous few chapters: a philosophy of taste, engagement, and identity. Today, in the midst of a rapid shift towards electrification and increasing automation in the name of progress, we instead look back at two artifacts that have formed a strong lineage for themselves throughout history, but yet are at the forefront of progress and innovation today and not in spite of: the Mazda Miata and the Land Rover Defender.`
                },
                {
                    title: "The Mazda Miata (MX-5)",
                    content: `The Mazda Miata, introduced in 1989, was not born from a desire to dominate sales in a conventional sense or even redefine luxury. Instead, it was idealized as a spiritual successor to lightweight British roadsters of the '60s, the likes of the Austin-Healey Sprite, Triumph Spitfire, and MG MGB. Curiously, as this was Mazda, this concept was reimagined from the then ubiquitous Japanese philosophy of precision and reliability. Mazda designers operated under a core principle of Jinba Ittai (人馬一体)–a term that translates to "horse and rider as one"; the car was to be an extension of the driver, not merely a mode of transportation. The Miata was designed to be the utmost expression of that philosophy, combined with the stripped-back back lightweight ethos of the British roadsters. Light, analog, and simple, it was designed to be fun. In an era where performance often equates to raw horsepower-driven straight line speed, the Miata made a different proposition: that pleasure could be found in mastery. The feedback from the manual transmission, the responsiveness of the steering due to its simplicity, and the carefully balanced chassis all contributed to an experience that was delightful. In many ways, it was an argument against overdesign. Where other manufacturers of the time sought to increase technological complexity and horsepower, Mazda doubled down on simplicity and purity with the Miata. Most importantly, the Miata retains this very philosophy to this very day, in spite of the monumental progress the automotive industry has undergone since its inception. Now on the tail end of its 4th generation in 2025, the Miata can still be described with the very keywords above: light, analog, simple. With a massive cult following, the Mazda Miata is one of the strongest case studies when it comes to preservation of its heritage and guiding philosophies within the automotive industry. With the fifth generation of the Mazda Miata looming, fans and industry analysts alike are asking the same question: What will Mazda do in the face of balancing progress and preservation? Will the fifth-generation Miata have a hybrid powertrain, resulting in a severe penalty in weight due to the heft of batteries? Or will it overcome the odds of exhaust emission regulations and retain the simplicity of a Naturally Aspirated engine? A tough place to be, undoubtedly.`
                },
                {
                    title: "The Land Rover Defender",
                    content: `Another marque facing this same dilemma with the same philosophy would be the Land Rover Defender; born with the purpose of utility, it was guided by the same principles of simplicity and reliability. First released in 1948, the Defender was the utilitarian workhorse of farms, safaris and military operations around the world. It was a tool–function over form, reliability over refinement. And for decades, it carried that identity with pride. Known for its boxy stance, it became an icon not because it changed, but because it didn't. However, as the automotive industry progressed, along with safety and emission regulations, the Land Rover Defender was forced to evolve accordingly; it now faced the challenge of adapt to these regulations that only add complexity and heft against a timeless lineage of simplicity and utility. In 2020, the reborn Defender was released, a vehicle that shares practically nothing with its predecessor, but instead relied heavily on its visual language to bear the torch forward. The unibody construction, touchscreen controls and air suspension of this new iteration mark a stark departure from its utilitarian ancestry. It became a vehicle caught between worlds; offering automation in the form of adaptive cruise control, while still invoking the ghost of a mud-caked original Defender in its boxy silhouette and proportions.`
                },
                {
                    title: "Where the marques differ",
                    content: `Unlike the Miata, Land Rover made the decision to reconcile its lineage with technological progress, and in its actions, might have found itself with a brand new demographic when it comes to the Defender. Both automakers here made conscious design decisions to retain the feeling of ritual, of experience, in their product offerings. The difference there is that Mazda opted to preserve the same exact ethos to this day–driving a Miata with a manual gearbox is an ultimate act of purity and mechanical finesse. Land Rover however, translated the utilitarian traits of the original Defender into ones that inform the modern Defender; what was boxy design simply due to the ease of manufacturing is now a symbolic presence on the roads. The original Defender sat higher on its suspension to allow it to cover all ground, today the modern Defender sits higher than many sedans on the roads; again, it is all about presence. While Miata drivers of today can still be found carving the back roads of Angeles Crest highway in a 2025 model year Miata, the same cant be said for a large majority of model year 2025 Defenders; where you'd likely see them instead parked on the driveways of Palm Springs and Palo Alto.

                    In many ways, the Miata and the Defender serve as prime examples of striking a balance between progress and preservation. They, ultimately, differ in their end destination in this balance. As the automotive industry continues its rapid transformation in the name of progress, these vehicles remind us that progress isn't always linear. They are future-aware, but past-grounded. At this point, you may be asking yourself this question: which of these approaches is the better one?
                    Me, personally, I'd pick the only option that still offers a manual transmission today, and I may or may not be writing this by the side of Angeles Crest Highway. (I'm not, I wish I was though).
                    
                    
                    
                    
                    `
                }
            ]
        }
    ]
}; 